version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"
    networks:
      - mongodb-net
    volumes:
      - mongodb-data:/data/db
networks:
  mongodb-net:

volumes:
  mongodb-data: